/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.coderbd.pos.design;

import com.coderbd.pos.constraints.Enum;
import com.coderbd.pos.constraints.Message;
import com.coderbd.pos.entity.Supplier;
import com.coderbd.pos.entity.User;
import com.coderbd.pos.service.SupplierService;
import com.coderbd.pos.utils.adder.SupplierAdder;
import com.coderbd.pos.validation.Valid;
import java.awt.Color;
import java.util.List;

/**
 *
 * @author Biswajit Debnath
 */
public class CreateSupplierPanel extends javax.swing.JPanel {

    private User user;
    private Supplier supplier;
    private List<Supplier> suppliers;
    private SupplierService supplierService;

    /**
     * Creates new form CreateSupplierPanel
     */
    public CreateSupplierPanel(User user, List<Supplier> suppliers, SupplierService supplierService) {
        this.user = user;
        this.supplier = new Supplier(user);
        this.suppliers = suppliers;
        this.supplierService = supplierService;
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        supplierNameField = new javax.swing.JTextField();
        supplierAddressField = new javax.swing.JTextField();
        supplierMobileField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        infoLabel = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel6.setText("jLabel6");

        jLabel1.setText("Supplier Name");

        jLabel4.setText("Supplier Address");

        jLabel5.setText("Supplier Mobile");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Add Supplier");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(supplierNameField)
                    .addComponent(supplierAddressField)
                    .addComponent(supplierMobileField)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 280, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(infoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierAddressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(supplierMobileField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(infoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:

        supplier.setSupplierName(supplierNameField.getText().toUpperCase());
        supplier.setSupplierAddress(supplierAddressField.getText().toUpperCase());
        supplier.setSupplierMobile(supplierMobileField.getText());

        if (supplier.getSupplierName() == null || supplier.getSupplierName().equals("")) {
            infoLabel.setForeground(Color.RED);
            infoLabel.setText(Message.ERROR_INVALID_INPUT);
        } else if (supplier.getSupplierAddress() == null || supplier.getSupplierAddress().equals("")) {
            infoLabel.setForeground(Color.RED);
            infoLabel.setText(Message.ERROR_INVALID_INPUT);
        } else if (supplier.getSupplierMobile() == null || supplier.getSupplierMobile().equals("") || !Valid.vMobile(supplier.getSupplierMobile())) {
            infoLabel.setForeground(Color.RED);
            infoLabel.setText(Message.ERROR_INVALID_INPUT);
        } else {
            int supplierId = supplierService.createSupplier(supplier);
            if (supplierId != Enum.invalidIndex) {
                infoLabel.setForeground(Color.GREEN);
                infoLabel.setText(Message.SUCCESS_SUPPLIER_ADDED);
                supplierAddressField.setText("");
                supplierNameField.setText("");
                supplierMobileField.setText("");
                supplier.setSupplierId(supplierId);
                System.out.println("SP: " + supplier);
                suppliers.add(supplier);
            } else {
                infoLabel.setForeground(Color.RED);
                infoLabel.setText(Message.ERROR_CONNECTION_ERROR);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField supplierAddressField;
    private javax.swing.JTextField supplierMobileField;
    private javax.swing.JTextField supplierNameField;
    // End of variables declaration//GEN-END:variables
}
